// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dbmessage.proto

#ifndef PROTOBUF_dbmessage_2eproto__INCLUDED
#define PROTOBUF_dbmessage_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_dbmessage_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsCMsgExecuteSqlRequestImpl();
void InitDefaultsCMsgExecuteSqlRequest();
void InitDefaultsCMsgExecuteSqlResponseImpl();
void InitDefaultsCMsgExecuteSqlResponse();
inline void InitDefaults() {
  InitDefaultsCMsgExecuteSqlRequest();
  InitDefaultsCMsgExecuteSqlResponse();
}
}  // namespace protobuf_dbmessage_2eproto
class CMsgExecuteSqlRequest;
class CMsgExecuteSqlRequestDefaultTypeInternal;
extern CMsgExecuteSqlRequestDefaultTypeInternal _CMsgExecuteSqlRequest_default_instance_;
class CMsgExecuteSqlResponse;
class CMsgExecuteSqlResponseDefaultTypeInternal;
extern CMsgExecuteSqlResponseDefaultTypeInternal _CMsgExecuteSqlResponse_default_instance_;

enum CMsgExecuteSqlRequest_Msg {
  CMsgExecuteSqlRequest_Msg_MsgID = 10001
};
bool CMsgExecuteSqlRequest_Msg_IsValid(int value);
const CMsgExecuteSqlRequest_Msg CMsgExecuteSqlRequest_Msg_Msg_MIN = CMsgExecuteSqlRequest_Msg_MsgID;
const CMsgExecuteSqlRequest_Msg CMsgExecuteSqlRequest_Msg_Msg_MAX = CMsgExecuteSqlRequest_Msg_MsgID;
const int CMsgExecuteSqlRequest_Msg_Msg_ARRAYSIZE = CMsgExecuteSqlRequest_Msg_Msg_MAX + 1;

const ::google::protobuf::EnumDescriptor* CMsgExecuteSqlRequest_Msg_descriptor();
inline const ::std::string& CMsgExecuteSqlRequest_Msg_Name(CMsgExecuteSqlRequest_Msg value) {
  return ::google::protobuf::internal::NameOfEnum(
    CMsgExecuteSqlRequest_Msg_descriptor(), value);
}
inline bool CMsgExecuteSqlRequest_Msg_Parse(
    const ::std::string& name, CMsgExecuteSqlRequest_Msg* value) {
  return ::google::protobuf::internal::ParseNamedEnum<CMsgExecuteSqlRequest_Msg>(
    CMsgExecuteSqlRequest_Msg_descriptor(), name, value);
}
enum CMsgExecuteSqlResponse_Msg {
  CMsgExecuteSqlResponse_Msg_MsgID = 10002
};
bool CMsgExecuteSqlResponse_Msg_IsValid(int value);
const CMsgExecuteSqlResponse_Msg CMsgExecuteSqlResponse_Msg_Msg_MIN = CMsgExecuteSqlResponse_Msg_MsgID;
const CMsgExecuteSqlResponse_Msg CMsgExecuteSqlResponse_Msg_Msg_MAX = CMsgExecuteSqlResponse_Msg_MsgID;
const int CMsgExecuteSqlResponse_Msg_Msg_ARRAYSIZE = CMsgExecuteSqlResponse_Msg_Msg_MAX + 1;

const ::google::protobuf::EnumDescriptor* CMsgExecuteSqlResponse_Msg_descriptor();
inline const ::std::string& CMsgExecuteSqlResponse_Msg_Name(CMsgExecuteSqlResponse_Msg value) {
  return ::google::protobuf::internal::NameOfEnum(
    CMsgExecuteSqlResponse_Msg_descriptor(), value);
}
inline bool CMsgExecuteSqlResponse_Msg_Parse(
    const ::std::string& name, CMsgExecuteSqlResponse_Msg* value) {
  return ::google::protobuf::internal::ParseNamedEnum<CMsgExecuteSqlResponse_Msg>(
    CMsgExecuteSqlResponse_Msg_descriptor(), name, value);
}
enum SQLTYPE {
  SELECT = 1,
  INSERT = 2,
  UPDATE = 3,
  DELETE = 4,
  CALL = 5
};
bool SQLTYPE_IsValid(int value);
const SQLTYPE SQLTYPE_MIN = SELECT;
const SQLTYPE SQLTYPE_MAX = CALL;
const int SQLTYPE_ARRAYSIZE = SQLTYPE_MAX + 1;

const ::google::protobuf::EnumDescriptor* SQLTYPE_descriptor();
inline const ::std::string& SQLTYPE_Name(SQLTYPE value) {
  return ::google::protobuf::internal::NameOfEnum(
    SQLTYPE_descriptor(), value);
}
inline bool SQLTYPE_Parse(
    const ::std::string& name, SQLTYPE* value) {
  return ::google::protobuf::internal::ParseNamedEnum<SQLTYPE>(
    SQLTYPE_descriptor(), name, value);
}
enum CALLBACK {
  MUSTCALLBACK = 1,
  NOTCALLBACK = 2
};
bool CALLBACK_IsValid(int value);
const CALLBACK CALLBACK_MIN = MUSTCALLBACK;
const CALLBACK CALLBACK_MAX = NOTCALLBACK;
const int CALLBACK_ARRAYSIZE = CALLBACK_MAX + 1;

const ::google::protobuf::EnumDescriptor* CALLBACK_descriptor();
inline const ::std::string& CALLBACK_Name(CALLBACK value) {
  return ::google::protobuf::internal::NameOfEnum(
    CALLBACK_descriptor(), value);
}
inline bool CALLBACK_Parse(
    const ::std::string& name, CALLBACK* value) {
  return ::google::protobuf::internal::ParseNamedEnum<CALLBACK>(
    CALLBACK_descriptor(), name, value);
}
enum BLOB {
  HASBLOB = 1,
  NONEBLOB = 2
};
bool BLOB_IsValid(int value);
const BLOB BLOB_MIN = HASBLOB;
const BLOB BLOB_MAX = NONEBLOB;
const int BLOB_ARRAYSIZE = BLOB_MAX + 1;

const ::google::protobuf::EnumDescriptor* BLOB_descriptor();
inline const ::std::string& BLOB_Name(BLOB value) {
  return ::google::protobuf::internal::NameOfEnum(
    BLOB_descriptor(), value);
}
inline bool BLOB_Parse(
    const ::std::string& name, BLOB* value) {
  return ::google::protobuf::internal::ParseNamedEnum<BLOB>(
    BLOB_descriptor(), name, value);
}
// ===================================================================

class CMsgExecuteSqlRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:CMsgExecuteSqlRequest) */ {
 public:
  CMsgExecuteSqlRequest();
  virtual ~CMsgExecuteSqlRequest();

  CMsgExecuteSqlRequest(const CMsgExecuteSqlRequest& from);

  inline CMsgExecuteSqlRequest& operator=(const CMsgExecuteSqlRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  CMsgExecuteSqlRequest(CMsgExecuteSqlRequest&& from) noexcept
    : CMsgExecuteSqlRequest() {
    *this = ::std::move(from);
  }

  inline CMsgExecuteSqlRequest& operator=(CMsgExecuteSqlRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CMsgExecuteSqlRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CMsgExecuteSqlRequest* internal_default_instance() {
    return reinterpret_cast<const CMsgExecuteSqlRequest*>(
               &_CMsgExecuteSqlRequest_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(CMsgExecuteSqlRequest* other);
  friend void swap(CMsgExecuteSqlRequest& a, CMsgExecuteSqlRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CMsgExecuteSqlRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  CMsgExecuteSqlRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const CMsgExecuteSqlRequest& from);
  void MergeFrom(const CMsgExecuteSqlRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(CMsgExecuteSqlRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef CMsgExecuteSqlRequest_Msg Msg;
  static const Msg MsgID =
    CMsgExecuteSqlRequest_Msg_MsgID;
  static inline bool Msg_IsValid(int value) {
    return CMsgExecuteSqlRequest_Msg_IsValid(value);
  }
  static const Msg Msg_MIN =
    CMsgExecuteSqlRequest_Msg_Msg_MIN;
  static const Msg Msg_MAX =
    CMsgExecuteSqlRequest_Msg_Msg_MAX;
  static const int Msg_ARRAYSIZE =
    CMsgExecuteSqlRequest_Msg_Msg_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Msg_descriptor() {
    return CMsgExecuteSqlRequest_Msg_descriptor();
  }
  static inline const ::std::string& Msg_Name(Msg value) {
    return CMsgExecuteSqlRequest_Msg_Name(value);
  }
  static inline bool Msg_Parse(const ::std::string& name,
      Msg* value) {
    return CMsgExecuteSqlRequest_Msg_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // optional string Sql = 7;
  bool has_sql() const;
  void clear_sql();
  static const int kSqlFieldNumber = 7;
  const ::std::string& sql() const;
  void set_sql(const ::std::string& value);
  #if LANG_CXX11
  void set_sql(::std::string&& value);
  #endif
  void set_sql(const char* value);
  void set_sql(const char* value, size_t size);
  ::std::string* mutable_sql();
  ::std::string* release_sql();
  void set_allocated_sql(::std::string* sql);

  // optional bytes Buffer = 9;
  bool has_buffer() const;
  void clear_buffer();
  static const int kBufferFieldNumber = 9;
  const ::std::string& buffer() const;
  void set_buffer(const ::std::string& value);
  #if LANG_CXX11
  void set_buffer(::std::string&& value);
  #endif
  void set_buffer(const char* value);
  void set_buffer(const void* value, size_t size);
  ::std::string* mutable_buffer();
  ::std::string* release_buffer();
  void set_allocated_buffer(::std::string* buffer);

  // optional string SQLWhere = 10;
  bool has_sqlwhere() const;
  void clear_sqlwhere();
  static const int kSQLWhereFieldNumber = 10;
  const ::std::string& sqlwhere() const;
  void set_sqlwhere(const ::std::string& value);
  #if LANG_CXX11
  void set_sqlwhere(::std::string&& value);
  #endif
  void set_sqlwhere(const char* value);
  void set_sqlwhere(const char* value, size_t size);
  ::std::string* mutable_sqlwhere();
  ::std::string* release_sqlwhere();
  void set_allocated_sqlwhere(::std::string* sqlwhere);

  // optional uint32 LogicType = 1;
  bool has_logictype() const;
  void clear_logictype();
  static const int kLogicTypeFieldNumber = 1;
  ::google::protobuf::uint32 logictype() const;
  void set_logictype(::google::protobuf::uint32 value);

  // optional uint32 SessionID = 2 [default = 0];
  bool has_sessionid() const;
  void clear_sessionid();
  static const int kSessionIDFieldNumber = 2;
  ::google::protobuf::uint32 sessionid() const;
  void set_sessionid(::google::protobuf::uint32 value);

  // optional uint64 TimeStamp = 3 [default = 0];
  bool has_timestamp() const;
  void clear_timestamp();
  static const int kTimeStampFieldNumber = 3;
  ::google::protobuf::uint64 timestamp() const;
  void set_timestamp(::google::protobuf::uint64 value);

  // optional uint64 TeamID = 4 [default = 0];
  bool has_teamid() const;
  void clear_teamid();
  static const int kTeamIDFieldNumber = 4;
  ::google::protobuf::uint64 teamid() const;
  void set_teamid(::google::protobuf::uint64 value);

  // optional uint32 BufSize = 8 [default = 0];
  bool has_bufsize() const;
  void clear_bufsize();
  static const int kBufSizeFieldNumber = 8;
  ::google::protobuf::uint32 bufsize() const;
  void set_bufsize(::google::protobuf::uint32 value);

  // optional uint32 OutNumber = 11 [default = 0];
  bool has_outnumber() const;
  void clear_outnumber();
  static const int kOutNumberFieldNumber = 11;
  ::google::protobuf::uint32 outnumber() const;
  void set_outnumber(::google::protobuf::uint32 value);

  // optional .BLOB HasBlob = 12;
  bool has_hasblob() const;
  void clear_hasblob();
  static const int kHasBlobFieldNumber = 12;
  ::BLOB hasblob() const;
  void set_hasblob(::BLOB value);

  // optional .SQLTYPE SqlType = 5 [default = SELECT];
  bool has_sqltype() const;
  void clear_sqltype();
  static const int kSqlTypeFieldNumber = 5;
  ::SQLTYPE sqltype() const;
  void set_sqltype(::SQLTYPE value);

  // optional .CALLBACK Callback = 6 [default = MUSTCALLBACK];
  bool has_callback() const;
  void clear_callback();
  static const int kCallbackFieldNumber = 6;
  ::CALLBACK callback() const;
  void set_callback(::CALLBACK value);

  // @@protoc_insertion_point(class_scope:CMsgExecuteSqlRequest)
 private:
  void set_has_logictype();
  void clear_has_logictype();
  void set_has_sessionid();
  void clear_has_sessionid();
  void set_has_timestamp();
  void clear_has_timestamp();
  void set_has_teamid();
  void clear_has_teamid();
  void set_has_sqltype();
  void clear_has_sqltype();
  void set_has_callback();
  void clear_has_callback();
  void set_has_sql();
  void clear_has_sql();
  void set_has_bufsize();
  void clear_has_bufsize();
  void set_has_buffer();
  void clear_has_buffer();
  void set_has_sqlwhere();
  void clear_has_sqlwhere();
  void set_has_outnumber();
  void clear_has_outnumber();
  void set_has_hasblob();
  void clear_has_hasblob();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr sql_;
  ::google::protobuf::internal::ArenaStringPtr buffer_;
  ::google::protobuf::internal::ArenaStringPtr sqlwhere_;
  ::google::protobuf::uint32 logictype_;
  ::google::protobuf::uint32 sessionid_;
  ::google::protobuf::uint64 timestamp_;
  ::google::protobuf::uint64 teamid_;
  ::google::protobuf::uint32 bufsize_;
  ::google::protobuf::uint32 outnumber_;
  int hasblob_;
  int sqltype_;
  int callback_;
  friend struct ::protobuf_dbmessage_2eproto::TableStruct;
  friend void ::protobuf_dbmessage_2eproto::InitDefaultsCMsgExecuteSqlRequestImpl();
};
// -------------------------------------------------------------------

class CMsgExecuteSqlResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:CMsgExecuteSqlResponse) */ {
 public:
  CMsgExecuteSqlResponse();
  virtual ~CMsgExecuteSqlResponse();

  CMsgExecuteSqlResponse(const CMsgExecuteSqlResponse& from);

  inline CMsgExecuteSqlResponse& operator=(const CMsgExecuteSqlResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  CMsgExecuteSqlResponse(CMsgExecuteSqlResponse&& from) noexcept
    : CMsgExecuteSqlResponse() {
    *this = ::std::move(from);
  }

  inline CMsgExecuteSqlResponse& operator=(CMsgExecuteSqlResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CMsgExecuteSqlResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CMsgExecuteSqlResponse* internal_default_instance() {
    return reinterpret_cast<const CMsgExecuteSqlResponse*>(
               &_CMsgExecuteSqlResponse_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(CMsgExecuteSqlResponse* other);
  friend void swap(CMsgExecuteSqlResponse& a, CMsgExecuteSqlResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CMsgExecuteSqlResponse* New() const PROTOBUF_FINAL { return New(NULL); }

  CMsgExecuteSqlResponse* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const CMsgExecuteSqlResponse& from);
  void MergeFrom(const CMsgExecuteSqlResponse& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(CMsgExecuteSqlResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef CMsgExecuteSqlResponse_Msg Msg;
  static const Msg MsgID =
    CMsgExecuteSqlResponse_Msg_MsgID;
  static inline bool Msg_IsValid(int value) {
    return CMsgExecuteSqlResponse_Msg_IsValid(value);
  }
  static const Msg Msg_MIN =
    CMsgExecuteSqlResponse_Msg_Msg_MIN;
  static const Msg Msg_MAX =
    CMsgExecuteSqlResponse_Msg_Msg_MAX;
  static const int Msg_ARRAYSIZE =
    CMsgExecuteSqlResponse_Msg_Msg_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Msg_descriptor() {
    return CMsgExecuteSqlResponse_Msg_descriptor();
  }
  static inline const ::std::string& Msg_Name(Msg value) {
    return CMsgExecuteSqlResponse_Msg_Name(value);
  }
  static inline bool Msg_Parse(const ::std::string& name,
      Msg* value) {
    return CMsgExecuteSqlResponse_Msg_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // repeated bytes FieldValue = 8;
  int fieldvalue_size() const;
  void clear_fieldvalue();
  static const int kFieldValueFieldNumber = 8;
  const ::std::string& fieldvalue(int index) const;
  ::std::string* mutable_fieldvalue(int index);
  void set_fieldvalue(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_fieldvalue(int index, ::std::string&& value);
  #endif
  void set_fieldvalue(int index, const char* value);
  void set_fieldvalue(int index, const void* value, size_t size);
  ::std::string* add_fieldvalue();
  void add_fieldvalue(const ::std::string& value);
  #if LANG_CXX11
  void add_fieldvalue(::std::string&& value);
  #endif
  void add_fieldvalue(const char* value);
  void add_fieldvalue(const void* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& fieldvalue() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_fieldvalue();

  // repeated uint32 FieldValueLen = 9;
  int fieldvaluelen_size() const;
  void clear_fieldvaluelen();
  static const int kFieldValueLenFieldNumber = 9;
  ::google::protobuf::uint32 fieldvaluelen(int index) const;
  void set_fieldvaluelen(int index, ::google::protobuf::uint32 value);
  void add_fieldvaluelen(::google::protobuf::uint32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      fieldvaluelen() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_fieldvaluelen();

  // optional uint32 LogicType = 1;
  bool has_logictype() const;
  void clear_logictype();
  static const int kLogicTypeFieldNumber = 1;
  ::google::protobuf::uint32 logictype() const;
  void set_logictype(::google::protobuf::uint32 value);

  // optional uint32 SessionID = 2;
  bool has_sessionid() const;
  void clear_sessionid();
  static const int kSessionIDFieldNumber = 2;
  ::google::protobuf::uint32 sessionid() const;
  void set_sessionid(::google::protobuf::uint32 value);

  // optional uint64 TimeStamp = 3;
  bool has_timestamp() const;
  void clear_timestamp();
  static const int kTimeStampFieldNumber = 3;
  ::google::protobuf::uint64 timestamp() const;
  void set_timestamp(::google::protobuf::uint64 value);

  // optional uint64 TeamID = 4;
  bool has_teamid() const;
  void clear_teamid();
  static const int kTeamIDFieldNumber = 4;
  ::google::protobuf::uint64 teamid() const;
  void set_teamid(::google::protobuf::uint64 value);

  // optional uint32 ResultCode = 5;
  bool has_resultcode() const;
  void clear_resultcode();
  static const int kResultCodeFieldNumber = 5;
  ::google::protobuf::uint32 resultcode() const;
  void set_resultcode(::google::protobuf::uint32 value);

  // optional uint32 RowCount = 6 [default = 0];
  bool has_rowcount() const;
  void clear_rowcount();
  static const int kRowCountFieldNumber = 6;
  ::google::protobuf::uint32 rowcount() const;
  void set_rowcount(::google::protobuf::uint32 value);

  // optional uint32 ColCount = 7 [default = 0];
  bool has_colcount() const;
  void clear_colcount();
  static const int kColCountFieldNumber = 7;
  ::google::protobuf::uint32 colcount() const;
  void set_colcount(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:CMsgExecuteSqlResponse)
 private:
  void set_has_logictype();
  void clear_has_logictype();
  void set_has_sessionid();
  void clear_has_sessionid();
  void set_has_timestamp();
  void clear_has_timestamp();
  void set_has_teamid();
  void clear_has_teamid();
  void set_has_resultcode();
  void clear_has_resultcode();
  void set_has_rowcount();
  void clear_has_rowcount();
  void set_has_colcount();
  void clear_has_colcount();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::std::string> fieldvalue_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > fieldvaluelen_;
  ::google::protobuf::uint32 logictype_;
  ::google::protobuf::uint32 sessionid_;
  ::google::protobuf::uint64 timestamp_;
  ::google::protobuf::uint64 teamid_;
  ::google::protobuf::uint32 resultcode_;
  ::google::protobuf::uint32 rowcount_;
  ::google::protobuf::uint32 colcount_;
  friend struct ::protobuf_dbmessage_2eproto::TableStruct;
  friend void ::protobuf_dbmessage_2eproto::InitDefaultsCMsgExecuteSqlResponseImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CMsgExecuteSqlRequest

// optional uint32 LogicType = 1;
inline bool CMsgExecuteSqlRequest::has_logictype() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void CMsgExecuteSqlRequest::set_has_logictype() {
  _has_bits_[0] |= 0x00000008u;
}
inline void CMsgExecuteSqlRequest::clear_has_logictype() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void CMsgExecuteSqlRequest::clear_logictype() {
  logictype_ = 0u;
  clear_has_logictype();
}
inline ::google::protobuf::uint32 CMsgExecuteSqlRequest::logictype() const {
  // @@protoc_insertion_point(field_get:CMsgExecuteSqlRequest.LogicType)
  return logictype_;
}
inline void CMsgExecuteSqlRequest::set_logictype(::google::protobuf::uint32 value) {
  set_has_logictype();
  logictype_ = value;
  // @@protoc_insertion_point(field_set:CMsgExecuteSqlRequest.LogicType)
}

// optional uint32 SessionID = 2 [default = 0];
inline bool CMsgExecuteSqlRequest::has_sessionid() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void CMsgExecuteSqlRequest::set_has_sessionid() {
  _has_bits_[0] |= 0x00000010u;
}
inline void CMsgExecuteSqlRequest::clear_has_sessionid() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void CMsgExecuteSqlRequest::clear_sessionid() {
  sessionid_ = 0u;
  clear_has_sessionid();
}
inline ::google::protobuf::uint32 CMsgExecuteSqlRequest::sessionid() const {
  // @@protoc_insertion_point(field_get:CMsgExecuteSqlRequest.SessionID)
  return sessionid_;
}
inline void CMsgExecuteSqlRequest::set_sessionid(::google::protobuf::uint32 value) {
  set_has_sessionid();
  sessionid_ = value;
  // @@protoc_insertion_point(field_set:CMsgExecuteSqlRequest.SessionID)
}

// optional uint64 TimeStamp = 3 [default = 0];
inline bool CMsgExecuteSqlRequest::has_timestamp() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void CMsgExecuteSqlRequest::set_has_timestamp() {
  _has_bits_[0] |= 0x00000020u;
}
inline void CMsgExecuteSqlRequest::clear_has_timestamp() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void CMsgExecuteSqlRequest::clear_timestamp() {
  timestamp_ = GOOGLE_ULONGLONG(0);
  clear_has_timestamp();
}
inline ::google::protobuf::uint64 CMsgExecuteSqlRequest::timestamp() const {
  // @@protoc_insertion_point(field_get:CMsgExecuteSqlRequest.TimeStamp)
  return timestamp_;
}
inline void CMsgExecuteSqlRequest::set_timestamp(::google::protobuf::uint64 value) {
  set_has_timestamp();
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:CMsgExecuteSqlRequest.TimeStamp)
}

// optional uint64 TeamID = 4 [default = 0];
inline bool CMsgExecuteSqlRequest::has_teamid() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void CMsgExecuteSqlRequest::set_has_teamid() {
  _has_bits_[0] |= 0x00000040u;
}
inline void CMsgExecuteSqlRequest::clear_has_teamid() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void CMsgExecuteSqlRequest::clear_teamid() {
  teamid_ = GOOGLE_ULONGLONG(0);
  clear_has_teamid();
}
inline ::google::protobuf::uint64 CMsgExecuteSqlRequest::teamid() const {
  // @@protoc_insertion_point(field_get:CMsgExecuteSqlRequest.TeamID)
  return teamid_;
}
inline void CMsgExecuteSqlRequest::set_teamid(::google::protobuf::uint64 value) {
  set_has_teamid();
  teamid_ = value;
  // @@protoc_insertion_point(field_set:CMsgExecuteSqlRequest.TeamID)
}

// optional .SQLTYPE SqlType = 5 [default = SELECT];
inline bool CMsgExecuteSqlRequest::has_sqltype() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void CMsgExecuteSqlRequest::set_has_sqltype() {
  _has_bits_[0] |= 0x00000400u;
}
inline void CMsgExecuteSqlRequest::clear_has_sqltype() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void CMsgExecuteSqlRequest::clear_sqltype() {
  sqltype_ = 1;
  clear_has_sqltype();
}
inline ::SQLTYPE CMsgExecuteSqlRequest::sqltype() const {
  // @@protoc_insertion_point(field_get:CMsgExecuteSqlRequest.SqlType)
  return static_cast< ::SQLTYPE >(sqltype_);
}
inline void CMsgExecuteSqlRequest::set_sqltype(::SQLTYPE value) {
  assert(::SQLTYPE_IsValid(value));
  set_has_sqltype();
  sqltype_ = value;
  // @@protoc_insertion_point(field_set:CMsgExecuteSqlRequest.SqlType)
}

// optional .CALLBACK Callback = 6 [default = MUSTCALLBACK];
inline bool CMsgExecuteSqlRequest::has_callback() const {
  return (_has_bits_[0] & 0x00000800u) != 0;
}
inline void CMsgExecuteSqlRequest::set_has_callback() {
  _has_bits_[0] |= 0x00000800u;
}
inline void CMsgExecuteSqlRequest::clear_has_callback() {
  _has_bits_[0] &= ~0x00000800u;
}
inline void CMsgExecuteSqlRequest::clear_callback() {
  callback_ = 1;
  clear_has_callback();
}
inline ::CALLBACK CMsgExecuteSqlRequest::callback() const {
  // @@protoc_insertion_point(field_get:CMsgExecuteSqlRequest.Callback)
  return static_cast< ::CALLBACK >(callback_);
}
inline void CMsgExecuteSqlRequest::set_callback(::CALLBACK value) {
  assert(::CALLBACK_IsValid(value));
  set_has_callback();
  callback_ = value;
  // @@protoc_insertion_point(field_set:CMsgExecuteSqlRequest.Callback)
}

// optional string Sql = 7;
inline bool CMsgExecuteSqlRequest::has_sql() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CMsgExecuteSqlRequest::set_has_sql() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CMsgExecuteSqlRequest::clear_has_sql() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CMsgExecuteSqlRequest::clear_sql() {
  sql_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_sql();
}
inline const ::std::string& CMsgExecuteSqlRequest::sql() const {
  // @@protoc_insertion_point(field_get:CMsgExecuteSqlRequest.Sql)
  return sql_.GetNoArena();
}
inline void CMsgExecuteSqlRequest::set_sql(const ::std::string& value) {
  set_has_sql();
  sql_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:CMsgExecuteSqlRequest.Sql)
}
#if LANG_CXX11
inline void CMsgExecuteSqlRequest::set_sql(::std::string&& value) {
  set_has_sql();
  sql_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:CMsgExecuteSqlRequest.Sql)
}
#endif
inline void CMsgExecuteSqlRequest::set_sql(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_sql();
  sql_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:CMsgExecuteSqlRequest.Sql)
}
inline void CMsgExecuteSqlRequest::set_sql(const char* value, size_t size) {
  set_has_sql();
  sql_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:CMsgExecuteSqlRequest.Sql)
}
inline ::std::string* CMsgExecuteSqlRequest::mutable_sql() {
  set_has_sql();
  // @@protoc_insertion_point(field_mutable:CMsgExecuteSqlRequest.Sql)
  return sql_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CMsgExecuteSqlRequest::release_sql() {
  // @@protoc_insertion_point(field_release:CMsgExecuteSqlRequest.Sql)
  clear_has_sql();
  return sql_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CMsgExecuteSqlRequest::set_allocated_sql(::std::string* sql) {
  if (sql != NULL) {
    set_has_sql();
  } else {
    clear_has_sql();
  }
  sql_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), sql);
  // @@protoc_insertion_point(field_set_allocated:CMsgExecuteSqlRequest.Sql)
}

// optional uint32 BufSize = 8 [default = 0];
inline bool CMsgExecuteSqlRequest::has_bufsize() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void CMsgExecuteSqlRequest::set_has_bufsize() {
  _has_bits_[0] |= 0x00000080u;
}
inline void CMsgExecuteSqlRequest::clear_has_bufsize() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void CMsgExecuteSqlRequest::clear_bufsize() {
  bufsize_ = 0u;
  clear_has_bufsize();
}
inline ::google::protobuf::uint32 CMsgExecuteSqlRequest::bufsize() const {
  // @@protoc_insertion_point(field_get:CMsgExecuteSqlRequest.BufSize)
  return bufsize_;
}
inline void CMsgExecuteSqlRequest::set_bufsize(::google::protobuf::uint32 value) {
  set_has_bufsize();
  bufsize_ = value;
  // @@protoc_insertion_point(field_set:CMsgExecuteSqlRequest.BufSize)
}

// optional bytes Buffer = 9;
inline bool CMsgExecuteSqlRequest::has_buffer() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CMsgExecuteSqlRequest::set_has_buffer() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CMsgExecuteSqlRequest::clear_has_buffer() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CMsgExecuteSqlRequest::clear_buffer() {
  buffer_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_buffer();
}
inline const ::std::string& CMsgExecuteSqlRequest::buffer() const {
  // @@protoc_insertion_point(field_get:CMsgExecuteSqlRequest.Buffer)
  return buffer_.GetNoArena();
}
inline void CMsgExecuteSqlRequest::set_buffer(const ::std::string& value) {
  set_has_buffer();
  buffer_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:CMsgExecuteSqlRequest.Buffer)
}
#if LANG_CXX11
inline void CMsgExecuteSqlRequest::set_buffer(::std::string&& value) {
  set_has_buffer();
  buffer_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:CMsgExecuteSqlRequest.Buffer)
}
#endif
inline void CMsgExecuteSqlRequest::set_buffer(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_buffer();
  buffer_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:CMsgExecuteSqlRequest.Buffer)
}
inline void CMsgExecuteSqlRequest::set_buffer(const void* value, size_t size) {
  set_has_buffer();
  buffer_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:CMsgExecuteSqlRequest.Buffer)
}
inline ::std::string* CMsgExecuteSqlRequest::mutable_buffer() {
  set_has_buffer();
  // @@protoc_insertion_point(field_mutable:CMsgExecuteSqlRequest.Buffer)
  return buffer_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CMsgExecuteSqlRequest::release_buffer() {
  // @@protoc_insertion_point(field_release:CMsgExecuteSqlRequest.Buffer)
  clear_has_buffer();
  return buffer_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CMsgExecuteSqlRequest::set_allocated_buffer(::std::string* buffer) {
  if (buffer != NULL) {
    set_has_buffer();
  } else {
    clear_has_buffer();
  }
  buffer_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), buffer);
  // @@protoc_insertion_point(field_set_allocated:CMsgExecuteSqlRequest.Buffer)
}

// optional string SQLWhere = 10;
inline bool CMsgExecuteSqlRequest::has_sqlwhere() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void CMsgExecuteSqlRequest::set_has_sqlwhere() {
  _has_bits_[0] |= 0x00000004u;
}
inline void CMsgExecuteSqlRequest::clear_has_sqlwhere() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void CMsgExecuteSqlRequest::clear_sqlwhere() {
  sqlwhere_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_sqlwhere();
}
inline const ::std::string& CMsgExecuteSqlRequest::sqlwhere() const {
  // @@protoc_insertion_point(field_get:CMsgExecuteSqlRequest.SQLWhere)
  return sqlwhere_.GetNoArena();
}
inline void CMsgExecuteSqlRequest::set_sqlwhere(const ::std::string& value) {
  set_has_sqlwhere();
  sqlwhere_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:CMsgExecuteSqlRequest.SQLWhere)
}
#if LANG_CXX11
inline void CMsgExecuteSqlRequest::set_sqlwhere(::std::string&& value) {
  set_has_sqlwhere();
  sqlwhere_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:CMsgExecuteSqlRequest.SQLWhere)
}
#endif
inline void CMsgExecuteSqlRequest::set_sqlwhere(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_sqlwhere();
  sqlwhere_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:CMsgExecuteSqlRequest.SQLWhere)
}
inline void CMsgExecuteSqlRequest::set_sqlwhere(const char* value, size_t size) {
  set_has_sqlwhere();
  sqlwhere_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:CMsgExecuteSqlRequest.SQLWhere)
}
inline ::std::string* CMsgExecuteSqlRequest::mutable_sqlwhere() {
  set_has_sqlwhere();
  // @@protoc_insertion_point(field_mutable:CMsgExecuteSqlRequest.SQLWhere)
  return sqlwhere_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CMsgExecuteSqlRequest::release_sqlwhere() {
  // @@protoc_insertion_point(field_release:CMsgExecuteSqlRequest.SQLWhere)
  clear_has_sqlwhere();
  return sqlwhere_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CMsgExecuteSqlRequest::set_allocated_sqlwhere(::std::string* sqlwhere) {
  if (sqlwhere != NULL) {
    set_has_sqlwhere();
  } else {
    clear_has_sqlwhere();
  }
  sqlwhere_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), sqlwhere);
  // @@protoc_insertion_point(field_set_allocated:CMsgExecuteSqlRequest.SQLWhere)
}

// optional uint32 OutNumber = 11 [default = 0];
inline bool CMsgExecuteSqlRequest::has_outnumber() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void CMsgExecuteSqlRequest::set_has_outnumber() {
  _has_bits_[0] |= 0x00000100u;
}
inline void CMsgExecuteSqlRequest::clear_has_outnumber() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void CMsgExecuteSqlRequest::clear_outnumber() {
  outnumber_ = 0u;
  clear_has_outnumber();
}
inline ::google::protobuf::uint32 CMsgExecuteSqlRequest::outnumber() const {
  // @@protoc_insertion_point(field_get:CMsgExecuteSqlRequest.OutNumber)
  return outnumber_;
}
inline void CMsgExecuteSqlRequest::set_outnumber(::google::protobuf::uint32 value) {
  set_has_outnumber();
  outnumber_ = value;
  // @@protoc_insertion_point(field_set:CMsgExecuteSqlRequest.OutNumber)
}

// optional .BLOB HasBlob = 12;
inline bool CMsgExecuteSqlRequest::has_hasblob() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void CMsgExecuteSqlRequest::set_has_hasblob() {
  _has_bits_[0] |= 0x00000200u;
}
inline void CMsgExecuteSqlRequest::clear_has_hasblob() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void CMsgExecuteSqlRequest::clear_hasblob() {
  hasblob_ = 1;
  clear_has_hasblob();
}
inline ::BLOB CMsgExecuteSqlRequest::hasblob() const {
  // @@protoc_insertion_point(field_get:CMsgExecuteSqlRequest.HasBlob)
  return static_cast< ::BLOB >(hasblob_);
}
inline void CMsgExecuteSqlRequest::set_hasblob(::BLOB value) {
  assert(::BLOB_IsValid(value));
  set_has_hasblob();
  hasblob_ = value;
  // @@protoc_insertion_point(field_set:CMsgExecuteSqlRequest.HasBlob)
}

// -------------------------------------------------------------------

// CMsgExecuteSqlResponse

// optional uint32 LogicType = 1;
inline bool CMsgExecuteSqlResponse::has_logictype() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CMsgExecuteSqlResponse::set_has_logictype() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CMsgExecuteSqlResponse::clear_has_logictype() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CMsgExecuteSqlResponse::clear_logictype() {
  logictype_ = 0u;
  clear_has_logictype();
}
inline ::google::protobuf::uint32 CMsgExecuteSqlResponse::logictype() const {
  // @@protoc_insertion_point(field_get:CMsgExecuteSqlResponse.LogicType)
  return logictype_;
}
inline void CMsgExecuteSqlResponse::set_logictype(::google::protobuf::uint32 value) {
  set_has_logictype();
  logictype_ = value;
  // @@protoc_insertion_point(field_set:CMsgExecuteSqlResponse.LogicType)
}

// optional uint32 SessionID = 2;
inline bool CMsgExecuteSqlResponse::has_sessionid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CMsgExecuteSqlResponse::set_has_sessionid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CMsgExecuteSqlResponse::clear_has_sessionid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CMsgExecuteSqlResponse::clear_sessionid() {
  sessionid_ = 0u;
  clear_has_sessionid();
}
inline ::google::protobuf::uint32 CMsgExecuteSqlResponse::sessionid() const {
  // @@protoc_insertion_point(field_get:CMsgExecuteSqlResponse.SessionID)
  return sessionid_;
}
inline void CMsgExecuteSqlResponse::set_sessionid(::google::protobuf::uint32 value) {
  set_has_sessionid();
  sessionid_ = value;
  // @@protoc_insertion_point(field_set:CMsgExecuteSqlResponse.SessionID)
}

// optional uint64 TimeStamp = 3;
inline bool CMsgExecuteSqlResponse::has_timestamp() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void CMsgExecuteSqlResponse::set_has_timestamp() {
  _has_bits_[0] |= 0x00000004u;
}
inline void CMsgExecuteSqlResponse::clear_has_timestamp() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void CMsgExecuteSqlResponse::clear_timestamp() {
  timestamp_ = GOOGLE_ULONGLONG(0);
  clear_has_timestamp();
}
inline ::google::protobuf::uint64 CMsgExecuteSqlResponse::timestamp() const {
  // @@protoc_insertion_point(field_get:CMsgExecuteSqlResponse.TimeStamp)
  return timestamp_;
}
inline void CMsgExecuteSqlResponse::set_timestamp(::google::protobuf::uint64 value) {
  set_has_timestamp();
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:CMsgExecuteSqlResponse.TimeStamp)
}

// optional uint64 TeamID = 4;
inline bool CMsgExecuteSqlResponse::has_teamid() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void CMsgExecuteSqlResponse::set_has_teamid() {
  _has_bits_[0] |= 0x00000008u;
}
inline void CMsgExecuteSqlResponse::clear_has_teamid() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void CMsgExecuteSqlResponse::clear_teamid() {
  teamid_ = GOOGLE_ULONGLONG(0);
  clear_has_teamid();
}
inline ::google::protobuf::uint64 CMsgExecuteSqlResponse::teamid() const {
  // @@protoc_insertion_point(field_get:CMsgExecuteSqlResponse.TeamID)
  return teamid_;
}
inline void CMsgExecuteSqlResponse::set_teamid(::google::protobuf::uint64 value) {
  set_has_teamid();
  teamid_ = value;
  // @@protoc_insertion_point(field_set:CMsgExecuteSqlResponse.TeamID)
}

// optional uint32 ResultCode = 5;
inline bool CMsgExecuteSqlResponse::has_resultcode() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void CMsgExecuteSqlResponse::set_has_resultcode() {
  _has_bits_[0] |= 0x00000010u;
}
inline void CMsgExecuteSqlResponse::clear_has_resultcode() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void CMsgExecuteSqlResponse::clear_resultcode() {
  resultcode_ = 0u;
  clear_has_resultcode();
}
inline ::google::protobuf::uint32 CMsgExecuteSqlResponse::resultcode() const {
  // @@protoc_insertion_point(field_get:CMsgExecuteSqlResponse.ResultCode)
  return resultcode_;
}
inline void CMsgExecuteSqlResponse::set_resultcode(::google::protobuf::uint32 value) {
  set_has_resultcode();
  resultcode_ = value;
  // @@protoc_insertion_point(field_set:CMsgExecuteSqlResponse.ResultCode)
}

// optional uint32 RowCount = 6 [default = 0];
inline bool CMsgExecuteSqlResponse::has_rowcount() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void CMsgExecuteSqlResponse::set_has_rowcount() {
  _has_bits_[0] |= 0x00000020u;
}
inline void CMsgExecuteSqlResponse::clear_has_rowcount() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void CMsgExecuteSqlResponse::clear_rowcount() {
  rowcount_ = 0u;
  clear_has_rowcount();
}
inline ::google::protobuf::uint32 CMsgExecuteSqlResponse::rowcount() const {
  // @@protoc_insertion_point(field_get:CMsgExecuteSqlResponse.RowCount)
  return rowcount_;
}
inline void CMsgExecuteSqlResponse::set_rowcount(::google::protobuf::uint32 value) {
  set_has_rowcount();
  rowcount_ = value;
  // @@protoc_insertion_point(field_set:CMsgExecuteSqlResponse.RowCount)
}

// optional uint32 ColCount = 7 [default = 0];
inline bool CMsgExecuteSqlResponse::has_colcount() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void CMsgExecuteSqlResponse::set_has_colcount() {
  _has_bits_[0] |= 0x00000040u;
}
inline void CMsgExecuteSqlResponse::clear_has_colcount() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void CMsgExecuteSqlResponse::clear_colcount() {
  colcount_ = 0u;
  clear_has_colcount();
}
inline ::google::protobuf::uint32 CMsgExecuteSqlResponse::colcount() const {
  // @@protoc_insertion_point(field_get:CMsgExecuteSqlResponse.ColCount)
  return colcount_;
}
inline void CMsgExecuteSqlResponse::set_colcount(::google::protobuf::uint32 value) {
  set_has_colcount();
  colcount_ = value;
  // @@protoc_insertion_point(field_set:CMsgExecuteSqlResponse.ColCount)
}

// repeated bytes FieldValue = 8;
inline int CMsgExecuteSqlResponse::fieldvalue_size() const {
  return fieldvalue_.size();
}
inline void CMsgExecuteSqlResponse::clear_fieldvalue() {
  fieldvalue_.Clear();
}
inline const ::std::string& CMsgExecuteSqlResponse::fieldvalue(int index) const {
  // @@protoc_insertion_point(field_get:CMsgExecuteSqlResponse.FieldValue)
  return fieldvalue_.Get(index);
}
inline ::std::string* CMsgExecuteSqlResponse::mutable_fieldvalue(int index) {
  // @@protoc_insertion_point(field_mutable:CMsgExecuteSqlResponse.FieldValue)
  return fieldvalue_.Mutable(index);
}
inline void CMsgExecuteSqlResponse::set_fieldvalue(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:CMsgExecuteSqlResponse.FieldValue)
  fieldvalue_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void CMsgExecuteSqlResponse::set_fieldvalue(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:CMsgExecuteSqlResponse.FieldValue)
  fieldvalue_.Mutable(index)->assign(std::move(value));
}
#endif
inline void CMsgExecuteSqlResponse::set_fieldvalue(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  fieldvalue_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:CMsgExecuteSqlResponse.FieldValue)
}
inline void CMsgExecuteSqlResponse::set_fieldvalue(int index, const void* value, size_t size) {
  fieldvalue_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:CMsgExecuteSqlResponse.FieldValue)
}
inline ::std::string* CMsgExecuteSqlResponse::add_fieldvalue() {
  // @@protoc_insertion_point(field_add_mutable:CMsgExecuteSqlResponse.FieldValue)
  return fieldvalue_.Add();
}
inline void CMsgExecuteSqlResponse::add_fieldvalue(const ::std::string& value) {
  fieldvalue_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:CMsgExecuteSqlResponse.FieldValue)
}
#if LANG_CXX11
inline void CMsgExecuteSqlResponse::add_fieldvalue(::std::string&& value) {
  fieldvalue_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:CMsgExecuteSqlResponse.FieldValue)
}
#endif
inline void CMsgExecuteSqlResponse::add_fieldvalue(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  fieldvalue_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:CMsgExecuteSqlResponse.FieldValue)
}
inline void CMsgExecuteSqlResponse::add_fieldvalue(const void* value, size_t size) {
  fieldvalue_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:CMsgExecuteSqlResponse.FieldValue)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
CMsgExecuteSqlResponse::fieldvalue() const {
  // @@protoc_insertion_point(field_list:CMsgExecuteSqlResponse.FieldValue)
  return fieldvalue_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
CMsgExecuteSqlResponse::mutable_fieldvalue() {
  // @@protoc_insertion_point(field_mutable_list:CMsgExecuteSqlResponse.FieldValue)
  return &fieldvalue_;
}

// repeated uint32 FieldValueLen = 9;
inline int CMsgExecuteSqlResponse::fieldvaluelen_size() const {
  return fieldvaluelen_.size();
}
inline void CMsgExecuteSqlResponse::clear_fieldvaluelen() {
  fieldvaluelen_.Clear();
}
inline ::google::protobuf::uint32 CMsgExecuteSqlResponse::fieldvaluelen(int index) const {
  // @@protoc_insertion_point(field_get:CMsgExecuteSqlResponse.FieldValueLen)
  return fieldvaluelen_.Get(index);
}
inline void CMsgExecuteSqlResponse::set_fieldvaluelen(int index, ::google::protobuf::uint32 value) {
  fieldvaluelen_.Set(index, value);
  // @@protoc_insertion_point(field_set:CMsgExecuteSqlResponse.FieldValueLen)
}
inline void CMsgExecuteSqlResponse::add_fieldvaluelen(::google::protobuf::uint32 value) {
  fieldvaluelen_.Add(value);
  // @@protoc_insertion_point(field_add:CMsgExecuteSqlResponse.FieldValueLen)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
CMsgExecuteSqlResponse::fieldvaluelen() const {
  // @@protoc_insertion_point(field_list:CMsgExecuteSqlResponse.FieldValueLen)
  return fieldvaluelen_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
CMsgExecuteSqlResponse::mutable_fieldvaluelen() {
  // @@protoc_insertion_point(field_mutable_list:CMsgExecuteSqlResponse.FieldValueLen)
  return &fieldvaluelen_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::CMsgExecuteSqlRequest_Msg> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::CMsgExecuteSqlRequest_Msg>() {
  return ::CMsgExecuteSqlRequest_Msg_descriptor();
}
template <> struct is_proto_enum< ::CMsgExecuteSqlResponse_Msg> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::CMsgExecuteSqlResponse_Msg>() {
  return ::CMsgExecuteSqlResponse_Msg_descriptor();
}
template <> struct is_proto_enum< ::SQLTYPE> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::SQLTYPE>() {
  return ::SQLTYPE_descriptor();
}
template <> struct is_proto_enum< ::CALLBACK> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::CALLBACK>() {
  return ::CALLBACK_descriptor();
}
template <> struct is_proto_enum< ::BLOB> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::BLOB>() {
  return ::BLOB_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_dbmessage_2eproto__INCLUDED
