/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class StructPass */

#ifndef _Included_StructPass
#define _Included_StructPass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     StructPass
 * Method:    toNativeStruct
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_StructPass_toNativeStruct
  (JNIEnv *, jobject);

/*
 * Class:     StructPass
 * Method:    fromNativeStruct
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_StructPass_fromNativeStruct
  (JNIEnv *, jobject);

/*
 * Class:     StructPass
 * Method:    initNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_StructPass_initNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
